services:
  mysql:
    image: mysql:8.0.20
    container_name: mecab_mysqlmysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: django_mysql_db
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
      TZ: 'Asia/Tokyo'
    command: >
      mysqld --default-authentication-plugin=mysql_native_password
    
    volumes:
    - 'mecab_mysql:/var/lib/mysql'

    ports:
    - 3306:3306

  web:
    build: .
    container_name: mecab_django_app
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      TZ: 'Asia/Tokyo'
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
        - mysql
    ports:
        - 8888:80
    environment:
        PMA_USER: mysql_user
        PMA_PASSWORD: mysql_password
        PMA_HOST: mysql
        TZ: 'Asia/Tokyo'
volumes:
  mecab_mysql:
    driver: local